dev_directory: ../dev_data
eval_directory: ../eval_data
model_directory: ./model
result_directory: ./result
result_file: result.csv

max_fpr: 0.1
decision_threshold: 0.9

feature:
  n_mels: 128
  n_frames: 5
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  lr: 0.001
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
